---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hzero-swagger
  labels:
    app: swagger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger
  template:
    metadata:
      labels:
        app: swagger
    spec:
      containers:
      - name: hzero-swagger
        image: registry.cn-hangzhou.aliyuncs.com/openhand/hzero-swagger:v1.4.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8050
          name: swagger
        env: 
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql.storage:3306/hzero_admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
        - name: SPRING_DATASOURCE_USERNAME
          value: hzero
        - name: SPRING_DATASOURCE_PASSWORD
          value: hzero2020.
        - name: SPRING_REDIS_HOST
          value: redis.storage
        - name: EUREKA_DEFAULT_ZONE
          value: http://hzero-register.hzero:8000/eureka
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://hzero-config:8010
        - name: HZERO_SWAGGER_BASE_URL
          value: http://172.23.40.42:30880
        - name: HZERO_GATEWAY_DOMAIN
          value: gateway.hzero.com.cn
        - name: JAVA_OPTS
          value: -Xms512m -Xmx1024m 
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1Gi
      imagePullSecrets:
        - name: registry-secret
