---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hzero-oauth
  labels:
    app: oauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth
  template:
    metadata:
      labels:
        app: oauth
    spec:
      containers:
      - name: hzero-oauth
        image: registry.cn-hangzhou.aliyuncs.com/openhand/hzero-oauth:v1.4.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8020
          name: oauth
        env: 
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql.storage:3306/hzero_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false
        - name: SPRING_DATASOURCE_USERNAME
          value: hzero
        - name: SPRING_DATASOURCE_PASSWORD
          value: hzero2020.
        - name: SPRING_REDIS_HOST
          value: redis.storage
        - name: EUREKA_DEFAULT_ZONE
          value: http://hzero-register.hzero:8000/eureka
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://hzero-config:8010
        - name: HZERO_OAUTH_LOGIN_SUCCESS_URL
          value: http://172.23.40.42:8848/workplace
        - name: JAVA_OPTS
          value: -Xms512m -Xmx1024m 
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1Gi
      imagePullSecrets:
        - name: registry-secret
