---
apiVersion: v1
kind: Service
metadata:
  name: hzero-gateway
  labels:
    app: gateway
spec:
  type: ClusterIP
  ports:
  - name: gateway
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: gateway
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hzero-gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: hzero-gateway
        image: registry.cn-hangzhou.aliyuncs.com/openhand/hzero-gateway:v1.4.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: gateway
        env: 
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql.storage:3306/hzero_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false
        - name: SPRING_DATASOURCE_USERNAME
          value: Rexxar
        - name: SPRING_DATASOURCE_PASSWORD
          value: Rexxar2022
        - name: SPRING_REDIS_HOST
          value: redis.storage
        - name: EUREKA_DEFAULT_ZONE
          value: http://hzero-register.hzero:8000/eureka
        - name: SPRING_CLOUD_CONFIG_ENABLED
          value: "false"
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://hzero-config:8010
        - name: JAVA_OPTS
          value: -Xms512m -Xmx1024m 
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1Gi
      imagePullSecrets:
        - name: registry-secret
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hzero-gateway
spec:
  rules:
  - host: gateway.7otech.com
    http:
      paths:
      - backend:
          serviceName: hzero-gateway
          servicePort: 8080
