---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hzero-message
  labels:
    app: message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message
  template:
    metadata:
      labels:
        app: message
    spec:
      containers:
      - name: hzero-message
        image: registry.cn-hangzhou.aliyuncs.com/openhand/hzero-message:v1.4.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8120
          name: message
        env: 
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql.storage:3306/hzero_message?useUnicode=true&characterEncoding=utf-8&useSSL=false
        - name: SPRING_DATASOURCE_USERNAME
          value: Rexxar
        - name: SPRING_DATASOURCE_PASSWORD
          value: Rexxar2022
        - name: SPRING_REDIS_HOST
          value: redis.storage
        - name: EUREKA_DEFAULT_ZONE
          value: http://hzero-register.hzero:8000/eureka
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://hzero-config:8010
        - name: JAVA_OPTS
          value: -Xms512m -Xmx1024m
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1Gi
      imagePullSecrets:
        - name: registry-secret
